name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Continuous Integration (CI)"]
    types: [completed]
    branches: [main]

jobs:
  deploy:

    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Redeploy Koyeb Service
        run: |
          koyeb service redeploy interesting-shanon/modul-2-ci-cd-devops